services:
  boss-timer:
    image: node:20-alpine
    working_dir: /app
    command: node /app/server.cjs
    volumes:
      - ./:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.bosswww.entrypoints=websecure
      - traefik.http.routers.bosswww.rule=Host(`www.tglabs.info`) && PathPrefix(`/boss`)
      - traefik.http.routers.bosswww.tls.certresolver=letsencrypt
      - traefik.http.services.bosswww.loadbalancer.server.port=5173
      - traefik.http.routers.bossredirect.entrypoints=websecure
      - traefik.http.routers.bossredirect.rule=Host(`bosstimer.tglabs.info`)
      - traefik.http.routers.bossredirect.tls.certresolver=letsencrypt
      - traefik.http.routers.bossredirect.middlewares=redirect-to-boss
      - traefik.http.middlewares.redirect-to-boss.redirectregex.regex=.*
      - traefik.http.middlewares.redirect-to-boss.redirectregex.replacement=https://www.tglabs.info/boss
      - traefik.http.middlewares.redirect-to-boss.redirectregex.permanent=true
    restart: unless-stopped
    network_mode: host
